In [1]:
# Importing the required packages
import numpy as np
import tensorly as tl
from tensorly.decomposition import matrix_product_state
from tensorly import tt_to_tensor

In [2]:
# Creating a tensor from a 12 x 12 matrix
tensor = tl.tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [3]:
# Obtaining the factors corresponding to Tensor Train Decomposition where we create 2 cores
factors = matrix_product_state(tensor, rank=[1,2,1])

In [4]:
# Printing the factors of decomposed tensor
len(factors)

2

In [5]:
 #Printing the core dimensions
 [f.shape for f in factors]

[(1, 12, 2), (2, 12, 1)]

In [6]:
#Retrieving our tensor from the decomposed version
print(np.round(tt_to_tensor(factors), decimals=10))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -0.  0.  1.  1.  1.  1. -0.  0. -0.  0.]
 [ 0.  0. -0.  0.  1.  1.  1.  1. -0.  0. -0.  0.]
 [ 0.  0. -0.  0.  1.  1.  1.  1. -0.  0. -0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0. -0.  0.  1.  1.  1.  1. -0.  0. -0.  0.]
 [ 0.  0. -0.  0.  1.  1.  1.  1. -0.  0. -0.  0.]
 [ 0.  0. -0.  0.  1.  1.  1.  1. -0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
